server:
  port: 8090
  servlet:
    context-path: /auth
spring:
  datasource:
    url: jdbc:mysql://mysql-auth-service:3306/auth-service-db
    username: sa
    password: password@123
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
keystore:
  filename: keystore.jks
  alias: server-alias
  password: passw0rd