server:
  port: 8096
  servlet:
    context-path: /auth
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth-service-db
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
keystore:
  filename: keystore.jks
  alias: server-alias
  password: passw0rd