server:
   port: 8096
spring:
   flyway:
      locations: "classpath:db/migration/dev"
   datasource:
      url: jdbc:mysql://localhost:3306/auth-service-db
      username: root
      password: password
      platform: mysql
      driverClassName: com.mysql.jdbc.Driver
      initalization-mode: always
   jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect
      database: MYSQL
      show-sql: 'true'
      hibernate:
         ddl-auto: none
         naming-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
keystore:
   filename: keystore.jks
   alias: server-alias
   password: passw0rd
