server:
  port: 8094
  servlet:
    context-path: /fare-service/v1/
  
spring:
  datasource:
    url: jdbc:h2:mem:faressDB
    driver-class-name: org.h2.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true