server:
  port: 80
  servlet:
    context-path: /v1/

spring:
  datasource:
    url: jdbc:mysql://mysql-fare-service:3306/fare-service-db
    username: sa
    password: password@123
    dbcp2:
      initial-size: 15
      max-total: 15
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect