server:
  port: 80
  servlet:
    context-path: /v1/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fare-service-db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect