server:
  port: 8094
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka
  
spring:
  datasource:
    url: jdbc:h2:mem:faresDB
    driver-class-name: org.h2.Driver
    username: root
    password: root
    dbcp2:
      initial-size: 15
      max-total: 15
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true