server:
  port: 80
  servlet:
    context-path: /v1/
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking-service-db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect