server:
  port: 80
  
spring:
  datasource:
    url: jdbc:mysql://mysql-booking-service:3306/booking-service-db
    username: sa  
    password: password@123
    dbcp2:
      initial-size: 15
      max-total: 15
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect