server:
  port: 8093
  servlet:
    context-path: /booking-service/v1/
  
spring:
  datasource:
    url: jdbc:h2:mem:bookingsDB
    driver-class-name: org.h2.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true