apiVersion: v1
kind: Service
metadata:
  name: mysql-auth-service
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  type: ClusterIP
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql-auth-service
        env:
        - name: MYSQL_DATABASE
          value: 'auth-service-db'
        # So you don't have to use root, but you can if you like
        - name: MYSQL_USER
          valueFrom:
             secretKeyRef:
               name: db-credentials
               key: mysql-user
         # You can use whatever password you like Use secret in real usage
        - name: MYSQL_PASSWORD
          valueFrom:
             secretKeyRef:
               name: db-credentials
               key: mysql-password'
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
             secretKeyRef:
               name: db-credentials
               key: mysql-root-password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage-auth
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage-auth
        persistentVolumeClaim:
          claimName: mysql-pv-claim-auth
