kind: Service
apiVersion: v1
metadata:
  name: search-service
spec:
  selector:
    app: search-service-lable
  ports:
  - protocol: TCP
    port: 8092
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service-deployment
spec:
  selector:
      matchLabels:
        app: search-service-lable
  replicas: 1
  template:
    metadata:
      labels:
        app: search-service-lable
    spec:
      containers:
        - name: booking-service-container
          image: gcr.io/invertible-tree-252704/booking-service:latest
          ports:
            - containerPort: 80
